// based on Colt Steele's original seedHelpers.js

module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Arroyo',
    'Diamond',
    'ABC',
    'XYZ',
    'Union',
    'Northern',
    'Southern',
    'Eastern',
    'Western',
    'Lycoris',
    'Chisato',
    'Lisa',
    'Takina',
    'Ruby',
    'Sapphire',
    'Kasumi',
    'Yukina',
    'Eve',
    'Owl',
    'Aozora',
    'Nova',
    'Saaya',
    'Dinosaur',
    'Tokyo',
    'Osaka',
    'Japan',
    'Underground',
    'Black',
    'Green',
    'Blue',
    'Purple',
    'Orange',
    'White',
    'Red'
];

module.exports.places = [
    'Hobbies',
    'Cards',
    'Collectibles',
    'Toys',
    'Games',
    'Card Store',
    'Card Shop',
    'Kingdom',
    'Cards & Toys',
    'Comics & Hobbies',
    'Card Cafe',
    'Playground',
    "Collectors' Home",
    'Circle',
    'Castle'
];

module.exports.games = ['magic', 'yugioh', 'pokemon', 'weiss', 'vanguard'];

module.exports.recurrence = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];